import React, { useState } from 'react';

const Product = () => {
  const [loading, setLoading] = useState(false);
  const [paymentSuccess, setPaymentSuccess] = useState(false);
  const [paymentInfo, setPaymentInfo] = useState(null);
  const [errorMessage, setErrorMessage] = useState('');

  // Sample Product Details
  const product = {
    title: 'Full-Stack MERN Course',
    description: 'Complete hands-on guide to building production-ready apps with Razorpay integration.',
    price: 499,
    currency: 'INR',
  };

  const handlePayment = async () => {
    setLoading(true);
    setErrorMessage('');
    setPaymentSuccess(false);

    try {
      // Step 1: Call your backend server to create Razorpay Order
      // Adjust the URL if your backend endpoint is on a different port or path
      const response = await fetch('http://localhost:3001/api/v1/payment/create-order', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          amount: product.price,
          currency: product.currency,
        }),
      });

      const data = await response.json();

      if (!response.ok || data.status !== 'success') {
        throw new Error(data.message || 'Failed to create order on server');
      }

      const { razorpayOrder } = data;

      // Step 2: Configure Razorpay Checkout Options
      const options = {
        key: 'YOUR_RAZORPAY_KEY_ID', // Replace with your Razorpay Key ID (e.g. rzp_test_xxxxx)
        amount: razorpayOrder.amount, // Amount in paise
        currency: razorpayOrder.currency,
        name: 'Razorpay Store',
        description: product.title,
        order_id: razorpayOrder.id, // Order ID generated by your server
        handler: function (razorpayResponse) {
          // Step 3: Payment completed successfully on Razorpay Popup
          console.log('Payment Response:', razorpayResponse);
          
          setPaymentInfo({
            paymentId: razorpayResponse.razorpay_payment_id,
            orderId: razorpayResponse.razorpay_order_id,
            signature: razorpayResponse.razorpay_signature,
            amount: product.price,
          });
          setPaymentSuccess(true);
          setLoading(false);

          // Optional: Send razorpayResponse to backend /verify-payment endpoint to verify signature
        },
        prefill: {
          name: 'Shivam Kumar',
          email: 'shivam@example.com',
          contact: '9876543210',
        },
        theme: {
          color: '#6366f1',
        },
        modal: {
          ondismiss: function () {
            setLoading(false);
          },
        },
      };

      // Step 4: Open Razorpay Popup
      if (window.Razorpay) {
        const rzp = new window.Razorpay(options);
        rzp.on('payment.failed', function (response) {
          console.error('Payment Failed:', response.error);
          setErrorMessage(response.error.description || 'Payment Failed');
          setLoading(false);
        });
        rzp.open();
      } else {
        throw new Error('Razorpay SDK failed to load. Check your internet connection or index.html script tag.');
      }
    } catch (error) {
      console.error('Payment Error:', error);
      setErrorMessage(error.message || 'Something went wrong');
      setLoading(false);
    }
  };

  return (
    <div className="product-card">
      <div className="product-image-container">
        <span className="product-tag">POPULAR</span>
        <div className="product-image-icon">🚀</div>
      </div>

      <h2 className="product-title">{product.title}</h2>
      <p className="product-description">{product.description}</p>

      <ul className="product-features">
        <li>
          <span className="feature-check">✓</span> 20+ Hours High-Quality Video Lessons
        </li>
        <li>
          <span className="feature-check">✓</span> Live Razorpay Payment Gateway Project
        </li>
        <li>
          <span className="feature-check">✓</span> Source Code & Lifetime Access
        </li>
      </ul>

      <div className="product-pricing">
        <div>
          <span className="price-label">One-time payment</span>
          <div className="price-amount">
            ₹{product.price} <span className="price-currency">{product.currency}</span>
          </div>
        </div>
      </div>

      {errorMessage && (
        <div style={{ color: '#f43f5e', fontSize: '0.85rem', marginBottom: '1rem', textAlign: 'center' }}>
          ⚠️ {errorMessage}
        </div>
      )}

      <button className="pay-button" onClick={handlePayment} disabled={loading}>
        {loading ? (
          <>
            <div className="spinner"></div>
            <span>Processing Order...</span>
          </>
        ) : (
          <span>Pay Now ₹{product.price}</span>
        )}
      </button>

      {/* Payment Success Receipt Display */}
      {paymentSuccess && paymentInfo && (
        <div className="receipt-card">
          <div className="receipt-header">
            <span>🎉</span>
            <span>Payment Successful!</span>
          </div>

          <div className="receipt-row">
            <span className="receipt-label">Amount Paid:</span>
            <span className="receipt-value">₹{paymentInfo.amount} INR</span>
          </div>

          <div className="receipt-row">
            <span className="receipt-label">Payment ID:</span>
            <span className="receipt-value">{paymentInfo.paymentId}</span>
          </div>

          <div className="receipt-row">
            <span className="receipt-label">Order ID:</span>
            <span className="receipt-value">{paymentInfo.orderId}</span>
          </div>

          <button className="btn-secondary" onClick={() => setPaymentSuccess(false)}>
            Close Receipt
          </button>
        </div>
      )}
    </div>
  );
};

export default Product;
